-- MySQL Script generated by MySQL Workbench
-- Sun Nov 28 06:19:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VolunteerHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VolunteerHistory` (
  `history_id` INT NOT NULL,
  `craeted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location` GEOMETRY NULL,
  `volunteer_id` VARCHAR(64) NOT NULL,
  `handicapped_id` VARCHAR(64) NOT NULL,
  `handicap_type` INT NULL,
  `handicap_level` INT NULL,
  `satisfaction` INT NULL,
  `thanks_comment` VARCHAR(256) NULL,
  `status` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  INDEX `user_id_idx` (`volunteer_id` ASC) VISIBLE,
  INDEX `handicapped_id_idx` (`handicapped_id` ASC) VISIBLE,
  CONSTRAINT `volunteer_id`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `handicapped_id`
    FOREIGN KEY (`handicapped_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VolunteerSummary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VolunteerSummary` (
  `summary_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `volunteer_id` VARCHAR(64) NULL,
  `handicap_type` INT NULL,
  `thanks_num` INT NULL,
  PRIMARY KEY (`summary_id`),
  INDEX `user_id_idx` (`volunteer_id` ASC) VISIBLE,
  CONSTRAINT `volunteer_id`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SnsId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SnsId` (
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `sns_id` VARCHAR(64) NOT NULL,
  `sns_type` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HandicapMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HandicapMaster` (
  `handicap_type` INT NOT NULL,
  `handicap_level` INT NOT NULL,
  `comment` VARCHAR(512) NULL,
  PRIMARY KEY (`handicap_type`, `handicap_level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HandicapInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HandicapInfo` (
  `handcapinfo_id` INT NOT NULL,
  `handicapped_id` VARCHAR(64) NOT NULL,
  `handcap_type` INT NOT NULL,
  `handicap_level` INT NOT NULL,
  `comment` VARCHAR(128) NULL,
  PRIMARY KEY (`handcapinfo_id`),
  INDEX `handicapped_id_idx` (`handicapped_id` ASC) VISIBLE,
  INDEX `handicap_type_idx` (`handcap_type` ASC) VISIBLE,
  INDEX `handicap_level_idx` (`handicap_level` ASC) VISIBLE,
  CONSTRAINT `handicapped_id`
    FOREIGN KEY (`handicapped_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `handicap_type`
    FOREIGN KEY (`handcap_type`)
    REFERENCES `mydb`.`HandicapMaster` (`handicap_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `handicap_level`
    FOREIGN KEY (`handicap_level`)
    REFERENCES `mydb`.`HandicapMaster` (`handicap_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `session_id` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` VARCHAR(64) NULL,
  PRIMARY KEY (`session_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Help`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Help` (
  `help_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `handicapped_id` VARCHAR(64) NULL,
  `volunteer_id` VARCHAR(64) NULL,
  `status` INT NULL COMMENT '助けを呼ぶ',
  PRIMARY KEY (`help_id`),
  INDEX `handicapped_id_idx` (`handicapped_id` ASC) VISIBLE,
  INDEX `volunteer_id_idx` (`volunteer_id` ASC) VISIBLE,
  CONSTRAINT `handicapped_id`
    FOREIGN KEY (`handicapped_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `volunteer_id`
    FOREIGN KEY (`volunteer_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CheckIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CheckIn` (
  `checkin_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `area_id` INT NULL,
  `user_id` VARCHAR(64) NULL,
  `sojourn_time` INT NULL,
  PRIMARY KEY (`checkin_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MyGeometry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MyGeometry` (
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `location` GEOMETRY NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
