version: '3.7'
services:
 swagger-editor:
   image: swaggerapi/swagger-editor
   ports:
     - "8001:8080"

 swagger-ui:
   image: swaggerapi/swagger-ui
   ports:
     - "8002:8080"
   volumes:
     - ./api/docs/swagger.yaml:/swagger.yaml
   environment:
     SWAGGER_JSON: swagger.yaml
